[build-system]
requires = ["setuptools",
            "setuptools_scm",
            "wheel",
            "cython==0.29.14",
            "jinja2==2.10.3",
            "oldest-supported-numpy",
            "extension-helpers"]
build-backend = 'setuptools.build_meta'

[tool.astropy-bot.autolabel]

# Comment this out to re-enable but then labeler Action needs to be disabled.
enabled = false
