name: Run tests

# TODO: cron on a separate YAML?
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
    - master
    - stable
    - LTS
  pull_request:
    branches:
    - master

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Code style checks
            os: ubuntu-latest
            python: 3.x
            toxenv: codestyle
          - name: Python 3.7 with minimal dependencies
            os: ubuntu-latest
            python: 3.7
            toxenv: py37-test
          - name: Python 3.8 with all optional dependencies
            os: ubuntu-latest
            python: 3.8
            toxenv: py38-test-alldeps
            toxposargs: --durations=50
            # compiler: clang
          # NOTE: In the build below we also check that tests do not open and
          # leave open any files. This has a performance impact on running the
          # tests, hence why it is not enabled by default.
          - name: Python 3.7 with oldest supported version of all dependencies
            os: ubuntu-latest
            python: 3.7
            toxenv: py37-test-oldestdeps
            toxposargs: --open-files
          - name: Python 3.7 with numpy 1.17 and full coverage
            os: ubuntu-latest
            python: 3.7
            toxenv: py37-test-alldeps-numpy117-cov-clocale
            toxposargs: --remote-data=astropy
          - name: Python 3.8 with all optional dependencies (Windows)
            os: windows-latest
            python: 3.8
            toxenv: py38-test-alldeps
          - name: Python 3.7 with remote data and dev version of key dependencies
            os: ubuntu-latest
            python: 3.7
            toxenv: py37-test-devdeps
            toxposargs: --remote-data=any

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install library dependencies
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get install language-pack-de tzdata
    - name: Install Python dependencies
      run: python -m pip install --upgrade tox codecov
    - name: Run tests
      run: |
        echo "CC="$CC
        echo "LC_CTYPE="$LC_CTYPE
        echo "LC_ALL="$LC_ALL
        tox ${{ matrix.toxargs}} -e ${{ matrix.toxenv}} -- ${{ matrix.toxposargs}}
    # TODO: Do we need --gcov-glob "*cextern*" ?
    - name: Coverage report
      uses: codecov/codecov-action@v1
